# Generated by Django 5.2.1 on 2025-05-13 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='floor_number',
        ),
        migrations.AddField(
            model_name='room',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
