# Generated by Django 5.2.1 on 2025-05-13 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_remove_room_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='amenities',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
