# Generated by Django 5.2.1 on 2025-05-14 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_room_amenities'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
