# Generated by Django 5.2.1 on 2025-05-14 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_reservation_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='amenities',
        ),
        migrations.AddField(
            model_name='table',
            name='amenities',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
