# Generated by Django 5.2.1 on 2025-05-16 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0006_remove_room_amenities_table_amenities'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='guest_email',
            field=models.TextField(help_text='Comma-separated list of emails', null=True),
        ),
    ]
