# Generated by Django 5.2.1 on 2025-05-18 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0007_reservation_guest_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='guest_type',
            field=models.TextField(null=True),
        ),
    ]
