# Generated by Django 5.2.1 on 2025-05-21 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0008_reservation_guest_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='guest_type',
        ),
        migrations.AddField(
            model_name='reservation',
            name='refreshments',
            field=models.TextField(null=True),
        ),
    ]
