# Generated by Django 5.2.1 on 2025-05-28 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0009_remove_reservation_guest_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='summary_pdf',
            field=models.FileField(blank=True, null=True, upload_to='reservation_pdfs/'),
        ),
    ]
